default_lang: ts
python:
  template: templates/python.py
  run: python solutions/python/run.py -y %%YEAR%% -d %%DAY%%
  workingdir: .
ts:
  template: templates/ts.ts
  run: npx ts-node run.ts -y %%YEAR%% -d %%DAY%%
purescript:
  template: templates/purescript.purs
  run: spago run --main Year%%YEAR%%.Day%%DAY%%
copilot:
  template: templates/copilot.ts
  run: npx ts-node run.ts -y %%YEAR%% -d %%DAY%%
picat:
  template: templates/picat.pi
  run: picat run.pi %%YEAR%%/%%DAY%%.pi
